<?php

namespace Database\Seeders;

use App\Models\GovernmentBond;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GovernmentBondSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bonds = [
            [
                'name' => 'Bon du Trésor Bénin 2024-2029',
                'issuer' => 'République du Bénin',
                'country' => 'Bénin',
                'isin_code' => 'BJBJ0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 6.50,
                'interest_type' => 'fixed',
                'payment_frequency' => 'semi_annual',
                'issue_date' => '2024-01-15',
                'maturity_date' => '2029-01-15',
                'maturity_years' => 5,
                'current_price' => 10000,
                'yield_to_maturity' => 6.50,
                'rating' => 'B+',
                'description' => 'Obligation souveraine émise par le gouvernement du Bénin pour financer des projets d\'infrastructure. Garantie par l\'État avec un taux d\'intérêt attractif de 6,50% versé semestriellement.',
                'risk_level' => 'medium',
                'minimum_investment' => 100000,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Obligation Assimilable du Trésor Côte d\'Ivoire 2024-2031',
                'issuer' => 'République de Côte d\'Ivoire',
                'country' => 'Côte d\'Ivoire',
                'isin_code' => 'CICI0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 6.75,
                'interest_type' => 'fixed',
                'payment_frequency' => 'annual',
                'issue_date' => '2024-03-01',
                'maturity_date' => '2031-03-01',
                'maturity_years' => 7,
                'current_price' => 10200,
                'yield_to_maturity' => 6.60,
                'rating' => 'BB-',
                'description' => 'OAT émise par la Côte d\'Ivoire avec une maturité de 7 ans. Taux fixe de 6,75% avec paiement annuel des coupons. Investissement sécurisé garanti par l\'État ivoirien.',
                'risk_level' => 'medium',
                'minimum_investment' => 500000,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Bon du Trésor Sénégal 2024-2027',
                'issuer' => 'République du Sénégal',
                'country' => 'Sénégal',
                'isin_code' => 'SNSN0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 5.95,
                'interest_type' => 'fixed',
                'payment_frequency' => 'semi_annual',
                'issue_date' => '2024-02-10',
                'maturity_date' => '2027-02-10',
                'maturity_years' => 3,
                'current_price' => 9950,
                'yield_to_maturity' => 6.10,
                'rating' => 'B+',
                'description' => 'Bon du Trésor à court terme émis par le Sénégal. Idéal pour les investisseurs recherchant une durée de placement plus courte avec un rendement stable de 5,95%.',
                'risk_level' => 'low',
                'minimum_investment' => 250000,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'Obligation UEMOA 2024-2034',
                'issuer' => 'UEMOA',
                'country' => 'Zone UEMOA',
                'isin_code' => 'UEMOA000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 5.50,
                'interest_type' => 'fixed',
                'payment_frequency' => 'annual',
                'issue_date' => '2024-06-01',
                'maturity_date' => '2034-06-01',
                'maturity_years' => 10,
                'current_price' => 10100,
                'yield_to_maturity' => 5.45,
                'rating' => 'BBB-',
                'description' => 'Obligation régionale émise par l\'UEMOA pour financer des projets d\'intégration économique. Durée longue de 10 ans avec un taux compétitif de 5,50%. Risque faible grâce à la garantie régionale.',
                'risk_level' => 'low',
                'minimum_investment' => 1000000,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Bon du Trésor Burkina Faso 2024-2028',
                'issuer' => 'République du Burkina Faso',
                'country' => 'Burkina Faso',
                'isin_code' => 'BFBF0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 6.25,
                'interest_type' => 'fixed',
                'payment_frequency' => 'semi_annual',
                'issue_date' => '2024-04-20',
                'maturity_date' => '2028-04-20',
                'maturity_years' => 4,
                'current_price' => 9900,
                'yield_to_maturity' => 6.40,
                'rating' => 'B',
                'description' => 'Obligation d\'État du Burkina Faso avec une maturité de 4 ans. Taux d\'intérêt fixe de 6,25% versé semestriellement. Bon équilibre entre rendement et durée d\'investissement.',
                'risk_level' => 'medium',
                'minimum_investment' => 200000,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Obligation Togo 2024-2030',
                'issuer' => 'République Togolaise',
                'country' => 'Togo',
                'isin_code' => 'TGTG0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 6.80,
                'interest_type' => 'fixed',
                'payment_frequency' => 'annual',
                'issue_date' => '2024-05-15',
                'maturity_date' => '2030-05-15',
                'maturity_years' => 6,
                'current_price' => 10050,
                'yield_to_maturity' => 6.75,
                'rating' => 'B',
                'description' => 'Obligation souveraine togolaise à 6 ans avec un taux attractif de 6,80%. Paiement annuel des intérêts. Investissement destiné au financement de projets de développement.',
                'risk_level' => 'medium',
                'minimum_investment' => 300000,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'Bon du Trésor Mali 2024-2026',
                'issuer' => 'République du Mali',
                'country' => 'Mali',
                'isin_code' => 'MLML0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 7.00,
                'interest_type' => 'fixed',
                'payment_frequency' => 'semi_annual',
                'issue_date' => '2024-07-01',
                'maturity_date' => '2026-07-01',
                'maturity_years' => 2,
                'current_price' => 9850,
                'yield_to_maturity' => 7.25,
                'rating' => 'B-',
                'description' => 'Bon du Trésor à court terme du Mali avec un taux d\'intérêt élevé de 7,00%. Maturité de 2 ans idéale pour les investisseurs recherchant un placement à court terme avec un rendement attractif.',
                'risk_level' => 'medium',
                'minimum_investment' => 150000,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'Obligation Niger 2024-2032',
                'issuer' => 'République du Niger',
                'country' => 'Niger',
                'isin_code' => 'NENE0000001',
                'nominal_value' => 10000,
                'currency' => 'FCFA',
                'interest_rate' => 6.90,
                'interest_type' => 'fixed',
                'payment_frequency' => 'annual',
                'issue_date' => '2024-08-10',
                'maturity_date' => '2032-08-10',
                'maturity_years' => 8,
                'current_price' => 10000,
                'yield_to_maturity' => 6.90,
                'rating' => 'B',
                'description' => 'Obligation à long terme émise par le Niger avec une maturité de 8 ans. Taux fixe de 6,90% avec versement annuel. Placement sécurisé garanti par l\'État nigérien.',
                'risk_level' => 'medium',
                'minimum_investment' => 400000,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($bonds as $bond) {
            GovernmentBond::create($bond);
        }
    }
}
